const letters: { [key: string]: string }[] = [
        { code: 'KeyQ', keyRus: 'й' },
        { code: 'KeyW', keyRus: 'ц' },
        { code: 'KeyE', keyRus: 'у' },
        { code: 'KeyR', keyRus: 'к' },
        { code: 'KeyT', keyRus: 'е' },
        { code: 'KeyY', keyRus: 'н' },
        { code: 'KeyU', keyRus: 'г' },
        { code: 'KeyI', keyRus: 'ш' },
        { code: 'KeyO', keyRus: 'щ' },
        { code: 'KeyP', keyRus: 'з' },
        { code: 'BracketLeft', keyRus: 'х' },
        { code: 'BracketRight', keyRus: 'ъ' },
        { code: 'KeyA', keyRus: 'ф' },
        { code: 'KeyS', keyRus: 'ы' },
        { code: 'KeyD', keyRus: 'в' },
        { code: 'KeyF', keyRus: 'а' },
        { code: 'KeyG', keyRus: 'п' },
        { code: 'KeyH', keyRus: 'р' },
        { code: 'KeyJ', keyRus: 'о' },
        { code: 'KeyK', keyRus: 'л' },
        { code: 'KeyL', keyRus: 'д' },
        { code: 'Semicolon', keyRus: 'ж' },
        { code: 'Quote', keyRus: 'э' },
        { code: 'Backslash', keyRus: 'ё' },
        { code: 'KeyZ', keyRus: 'я' },
        { code: 'KeyX', keyRus: 'ч' },
        { code: 'KeyC', keyRus: 'с' },
        { code: 'KeyV', keyRus: 'м' },
        { code: 'KeyB', keyRus: 'и' },
        { code: 'KeyN', keyRus: 'т' },
        { code: 'KeyM', keyRus: 'ь' },
        { code: 'Comma', keyRus: 'б' },
        { code: 'Period', keyRus: 'ю' },
        { code: 'Slash', keyRus: '/' },
        { code: 'Space', keyRus: ' ' },
    ]

    const words: { [key: number]: string[]} = {
        1: ['автор', '著者、作者', ''],
        2: ['адрес', '住所、番地', ''],
        3: ['белый','①白い ②淡色の',''],
        4: ['давно','①ずっと以前に ②長い間',''],
        5: ['живот','腹、お腹',''],
        6: ['камень','石、岩石',''],
        7: ['шаг','歩調/足音',''],
        8: ['наука','科学/学問',''],
        9: ['фирма','会社',''],
        10: ['начало','はじめ',''],
    }

export default letters;
